#!/usr/bin/env php
<?php declare(strict_types=1);

if(php_sapi_name()!= "cli")
{
  fwrite(STDERR,
  PHP_EOL."Fichier uniquement pour ligne de commande".PHP_EOL);
  die(1);
}

$demo = false;
foreach($argv as $value)
{
  if($value === "--demo")
  {
    $demo = true;
  }
  if($value === "-h" || $value === "--help")
  {
    echo PHP_EOL."Pour insérer les données de demo utilisez le flag --demo".PHP_EOL;
    exit();
  }
}

require_once '/var/www/vendor/autoload.php';

$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbcontainer = getenv('CONTAINER_MYSQL');

$pdo = new PDO("mysql:host=$dbcontainer;dbname=$dbname", $dbuser, $dbpassword);

/**
* Suppression de table
*/ 
echo "[||";
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');


$pdo->exec('DROP TABLE users');
$pdo->exec('DROP TABLE salons');
$pdo->exec('DROP TABLE ranks');
$pdo->exec('DROP TABLE users_salons');


$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

/**
 * creation tables
 * 
 */



$pdo->exec("CREATE TABLE `users` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `pseudo` varchar(255) NOT NULL,
  `isReady` tinyint(1) NOT NULL DEFAULT 0,  
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY(id)
)");

$pdo->exec("CREATE TABLE `ranks` (
  `id_ranks` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) NOT NULL,
  `img` varchar(255) NOT NULL,
  PRIMARY KEY(id_ranks)
)");


$pdo->exec("CREATE TABLE `salons` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) NOT NULL,
  `ranks_img` varchar(255) NOT NULL,
  PRIMARY KEY(id)
)");

// creation table liaison
$pdo->exec("CREATE TABLE users_salons(
  users_id int(11) UNSIGNED NOT NULL,
  salons_id int(11) UNSIGNED NOT NULL,
  PRIMARY KEY(users_id, salons_id),
  CONSTRAINT fk_users
      FOREIGN KEY(users_id)
      REFERENCES users(id)
      ON DELETE CASCADE
      ON UPDATE RESTRICT,
  CONSTRAINT fk_salons
      FOREIGN KEY(salons_id)
      REFERENCES salons(id)
      ON DELETE CASCADE
      ON UPDATE RESTRICT
)");


echo "||||||||||||]";



/**
 * remplissage des tables
 */

if($demo == true){

  echo PHP_EOL."Mode Demo actif !".PHP_EOL;
  echo "[||";

// Insertion des ranks dans la bdd
$pdo->exec("INSERT INTO `ranks` (`id_ranks`, `nom`, `img`) VALUES
(1, 'Bronze 1', 'www/public/assets/img/ranks/Bronze1.jpg'),
(2, 'Bronze 2', 'www/public/assets/img/ranks/Bronze2.jpg'), 
(3, 'Bronze 3', 'www/public/assets/img/ranks/Bronze3.jpg'), 
(4, 'Argent 1', 'www/public/assets/img/ranks/Argent1.jpg'), 
(5, 'Argent 2', 'www/public/assets/img/ranks/Argent2.jpg'), 
(6, 'Argent 3', 'www/public/assets/img/ranks/Argent3.jpg'),
(7, 'Or 1', 'www/public/assets/img/ranks/Or1.jpg'),
(8, 'Or 2', 'www/public/assets/img/ranks/Or2.jpg'), 
(9, 'Or 3', 'www/public/assets/img/ranks/Or3.jpg'),
(10, 'Platine 1', 'www/public/assets/img/ranks/Platine1.jpg'),
(11, 'Platine 2', 'www/public/assets/img/ranks/Platine2.jpg'),
(12, 'Platine 3', 'www/public/assets/img/ranks/Platine3.jpg'),
(13, 'Diamand 1', 'www/public/assets/img/ranks/Diamand1.jpg'),
(14, 'Diamand 2', 'www/public/assets/img/ranks/Diamand2.jpg'),
(15, 'Diamand 3', 'www/public/assets/img/ranks/Diamand3.jpg'),
(16, 'Champion 1', 'www/public/assets/img/ranks/Champion1.jpg'),
(17, 'Champion 2', 'www/public/assets/img/ranks/Champion2.jpg'),
(18, 'Champion 3', 'www/public/assets/img/ranks/Champion3.jpg'),
(19, 'Grand Champion', 'www/public/assets/img/ranks/GrandChampion.jpg')
");

echo "||||||||||";

// Insertion des salons prédifini dans la bdd
$pdo->exec("INSERT INTO salons (`nom`, `ranks_img`) VALUES 
('Groupe Bronze 1', 'www/public/assets/img/ranks/Bronze1.jpg'),
('Groupe Bronze 2', 'www/public/assets/img/ranks/Bronze2.jpg'), 
('Groupe Bronze 3', 'www/public/assets/img/ranks/Bronze3.jpg'), 
('Groupe Argent 1', 'www/public/assets/img/ranks/Argent1.jpg'), 
('Groupe Argent 2', 'www/public/assets/img/ranks/Argent2.jpg'), 
('Groupe Argent 3', 'www/public/assets/img/ranks/Argent3.jpg'),
('Groupe Or 1', 'www/public/assets/img/ranks/Or1.jpg'),
('Groupe Or 2', 'www/public/assets/img/ranks/Or2.jpg'), 
('Groupe Or 3', 'www/public/assets/img/ranks/Or3.jpg'),
('Groupe Platine 1', 'www/public/assets/img/ranks/Platine1.jpg'),
('Groupe Platine 2', 'www/public/assets/img/ranks/Platine2.jpg'),
('Groupe Platine 3', 'www/public/assets/img/ranks/Platine3.jpg'),
('Groupe Diamand 1', 'www/public/assets/img/ranks/Diamand1.jpg'),
('Groupe Diamand 2', 'www/public/assets/img/ranks/Diamand2.jpg'),
('Groupe Diamand 3', 'www/public/assets/img/ranks/Diamand3.jpg'),
('Groupe Champion 1', 'www/public/assets/img/ranks/Champion1.jpg'),
('Groupe Champion 2', 'www/public/assets/img/ranks/Champion2.jpg'),
('Groupe Champion 3', 'www/public/assets/img/ranks/Champion3.jpg'),
('Groupe Grand Champion', 'www/public/assets/img/ranks/GrandChampion.jpg')
");
echo "||";

$password = password_hash('admin', PASSWORD_BCRYPT);

$pdo->exec(
        "INSERT INTO users SET
        email='admin@admin.fr',
        password='{$password}',
        pseudo='BigAdmin',
        isReady=0
        ");

echo "||||]".PHP_EOL;
}